export const metadata = {
  title: 'Privacy Policy — Praecora',
}

export default function PrivacyPage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-16 md:px-6 md:py-24">
      <h1 className="text-balance text-4xl font-bold tracking-tight text-neutral-950 md:text-5xl">
        Privacy Policy
      </h1>
      <p className="mt-3 text-sm text-neutral-500">
        Last updated:{' '}
        {new Date().toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        })}
      </p>

      <div className="mt-12 space-y-10 text-neutral-700">
        <section>
          <h2 className="text-xl font-semibold text-neutral-950">What we collect</h2>
          <p className="mt-3 text-base leading-relaxed">
            We collect information you provide when you sign up (name, email, payment
            information via Stripe), data generated by your use of the platform (deals,
            conversations, contacts), and information about the artists and contacts you
            engage with through the service (Instagram handles, public profile data,
            contact information you supply).
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-neutral-950">How we use it</h2>
          <p className="mt-3 text-base leading-relaxed">
            We use your data to operate the platform on your behalf — generate
            personalized outreach across Instagram and email, route replies, manage your
            pipeline, and bill your account. We do not sell or share your data with third
            parties for their marketing purposes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-neutral-950">Third-party services</h2>
          <p className="mt-3 text-base leading-relaxed">
            We use trusted third-party services to operate the platform, including
            database, hosting, payments, AI, and email infrastructure providers. Each is
            bound by their own privacy commitments.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-neutral-950">Outreach contact data</h2>
          <p className="mt-3 text-base leading-relaxed">
            Because our service involves outreach, we process publicly available profile
            information about the artists and contacts you engage with. We do not access
            private messages outside the conversations you initiate. We retain this data
            only as long as needed to operate your outreach and pipeline.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-neutral-950">Your rights</h2>
          <p className="mt-3 text-base leading-relaxed">
            You can export your data, request deletion, or close your account at any
            time. Email{' '}
            <a
              href="mailto:privacy@praecora.com"
              className="font-medium text-neutral-950 underline underline-offset-2 hover:no-underline"
            >
              privacy@praecora.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-neutral-950">Changes</h2>
          <p className="mt-3 text-base leading-relaxed">
            We may update this policy as the platform evolves. Material changes will be
            announced via email to active customers.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-neutral-950">Contact</h2>
          <p className="mt-3 text-base leading-relaxed">
            Questions:{' '}
            <a
              href="mailto:privacy@praecora.com"
              className="font-medium text-neutral-950 underline underline-offset-2 hover:no-underline"
            >
              privacy@praecora.com
            </a>
          </p>
        </section>
      </div>
    </div>
  )
}
