export const metadata = {
  title: 'Privacy Policy — CrateHQ',
}

export default function PrivacyPage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-16 md:px-6 md:py-24">
      <h1 className="font-[var(--font-heading)] text-4xl italic md:text-5xl">
        Privacy Policy
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
      </p>

      <div className="prose prose-invert mt-10 max-w-none space-y-8 text-foreground/90">
        <section>
          <h2 className="text-xl font-semibold text-foreground">What we collect</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            We collect information you provide when you sign up (name, email, payment
            information via Stripe), data generated by your use of the platform (deals,
            conversations, contacts), and information about the artists and contacts you
            engage with through the service (Instagram handles, public profile data,
            contact information you supply).
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">How we use it</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            We use your data to operate the platform on your behalf — generate
            personalized outreach, route replies, manage your pipeline, and bill your
            account. We do not sell or share your data with third parties for their
            marketing purposes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">Third-party services</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            We use trusted third-party services to operate the platform, including
            Supabase (database + auth), Vercel (hosting), Stripe (payments), Anthropic
            (AI), and other infrastructure providers. Each is bound by their own privacy
            commitments.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">Instagram contact data</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            Because our service involves Instagram outreach, we process publicly
            available profile information about the artists and contacts you engage
            with. We do not access private messages outside the conversations you
            initiate. We retain this data only as long as needed to operate your
            outreach and pipeline.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">Your rights</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            You can export your data, request deletion, or close your account at any
            time. Email <a href="mailto:privacy@cratehq.io" className="text-primary hover:underline">privacy@cratehq.io</a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">Changes</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            We may update this policy as the platform evolves. Material changes will be
            announced via email to active customers.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground">Contact</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            Questions: <a href="mailto:privacy@cratehq.io" className="text-primary hover:underline">privacy@cratehq.io</a>
          </p>
        </section>
      </div>
    </div>
  )
}
